# -*- coding: utf-8 -*-
"""CS-13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ll3qJdtzC7fAZKCImZernoUgAtv46-py

Write a C program to read temperature in centigrade and display a suitable message according to temperature state below :
Temp < 0 then Freezing weather
Temp 0-10 then Very Cold weather
Temp 10-20 then Cold weather
Temp 20-30 then Normal 
Temp 30-40 then Its Hot
Temp >=40 then Its Very Hot
"""

temp = float(input("Enter tenperature in centigrade: "))

if(temp<0):
    print("Freezing weather")
elif(temp>=0 and temp<=10):
    print("Very Cold weather")
elif(temp>10 and temp<=20):
    print("Cold weather")
elif(temp>20 and temp<=30):
    print("Normal temp")
elif(temp>30 and temp<=40):
    print("Its Hot")
elif(temp>40):
    print("Its Very Hot")