# -*- coding: utf-8 -*-
"""CS-15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIl9y6mTNEEgyk9FC-JH_nqrcT0IaD1F

Write a program in C to calculate and print the Electricity bill of a given customer. The customer id., name and unit consumed by the user should be taken from the keyboard and display the total amount to pay to the customer. The charge are as follow :

Unit---Charge/unit

upto 199	@1.20

200 and above but less than 400	@1.50

400 and above but less than 600	@1.80

600 and above	@2.00

If bill exceeds Rs. 400 then a surcharge of 15% will be charged and the minimum bill should be of Rs. 100/-
"""

id = int(input("Enter your id: "))
name = input("Enter your name: ")
unit = float(input("Consumed amount: "))

if(unit<=199):
    charge = 1.20
elif(unit>199 and unit<400):
    charge = 1.50
elif(unit>=400 and unit<600):
    charge = 1.80
else:
    charge = 2.00

consumed_amnt_charge = unit*charge

if(consumed_amnt_charge>400):
    surcharge = (consumed_amnt_charge*15)/100
else:
    surcharge = 0

total_bill = consumed_amnt_charge+surcharge

if(total_bill<100):
    total_bill = 100

print("\nCustomer ID:",id)
print("Customer Name:",name)
print("Unit consumed:",unit)
print(f"Amount Charges @bdt. {charge} per unit : {consumed_amnt_charge}")
print("Surcharge amount:",surcharge)
print("Net Amount Paid By the Customer:",total_bill)