# -*- coding: utf-8 -*-
"""CS-14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arGv2YFLeHrkpWjMJWpboXeiHVFW94bi

Write a C program to check whether a triangle is Equilateral, Isosceles or Scalene.

Equilateral triangle: An equilateral triangle is a triangle in which all three sides are equal. In the familiar Euclidean geometry, equilateral triangles are also equiangular; that is, all three internal angles are also congruent to each other and are each 60°.

Isosceles triangle: An isosceles triangle is a triangle that has two sides of equal length.

Scalene triangle: A scalene triangle is a triangle that has three unequal sides
"""

a,b,c = input("Enter three sides of a triangle: ").split()

if(int(a)==int(b) and int(b)==int(c)):
    print("Equilateral triangle")
elif(int(a)==int(b) or int(a)==int(c) or int(b)==int(c)):
    print("Isosceles triangle")
else:
    print("Scalene triangle")