# -*- coding: utf-8 -*-
"""CS-11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezSPlV1gLEP4oAYn5AsgoleUdMLOrDZk

Write a program to calculate the root of a Quadratic Equation
"""

import math
x,y,z = input("Input the value of a b c:").split()

a = int(x)
b = int(y)
c = int(z)

d = ((b*b)-(4*a*c))

if(d==0):
    root1 = -b/(2*a)
    root2 = -b/(2*a)
    print("root1:",root1)
    print("root2:",root2)

elif(d>0):
    root1 = (-b+math.sqrt(d))/(2*a)
    root2 = (-b-math.sqrt(d))/(2*a)
    print("root1:",root1)
    print("root2:",root2)

else:
    print("Root are imaginary")