# -*- coding: utf-8 -*-
"""CS-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Grz2t224lJYpiWMZYy-4V9LCWEVAOhXl

Write a program to accept two integers and check whether they are equal or not
"""

a = int(input("Enter a number:"))
b = int(input("Enter another number:"))

if(a==b):
    print("The numbers are equal")
else:
    print("The numbers are not Equal")