# -*- coding: utf-8 -*-
"""CS-10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnFPofGroyeLerdqPvKaHr6ISanmYguu

Write a program to find the eligibility of admission for a professional course based on the following criteria:

Eligibility Criteria : Marks in Maths >=65 and Marks in Phy >=55 and Marks in Chem>=50 and Total in all three subject >=190 or Total in Maths and Physics >=140 ---Input the marks obtained in Physics :65 Input the marks obtained in Chemistry :51 Input the marks obtained in Mathematics :72 Total marks of Maths, Physics and Chemistry : 188 Total marks of Maths and Physics : 137 The candidate is not eligible.
"""

math_marks = int(input("Enter your marks in math:"))
phy_marks = int(input("Enter your marks in physics:"))
chem_marks = int(input("Enter your marks in chemistry:"))

if(math_marks>=65 and phy_marks>=55 and chem_marks>=50):
    if(math_marks+phy_marks+chem_marks>=190):
        print("The candidate is eligible for admission.")
    elif(math_marks+phy_marks>=140):
        print("The candidate is eligible for admission.")
    else:
        print("The candidate is not eligible for admission.")
else:
    print("The candidate is not eligible for admission.")