# -*- coding: utf-8 -*-
"""CS-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AkjqzP28shNVUaq6B93P1zyfzB1rT47V

Write a program to check whether a given number is even or odd
"""

a = input("Enter a number greater than 0:")

try:
    b = int(a)
    if(b>=0):
        if(b%2 == 0):
            print("The number is Even")
        else:
            print("The number is Odd")
    else:
        print("You entered negative number")
except:
    print("Please enter number")