# -*- coding: utf-8 -*-
"""CS-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nNhaxVrSutbnsgR85admE7kkTtxEKahO

Write a program to check whether a given number is positive or negative
"""

a = int(input("Enter any number:"))
if(a>=0):
    print("The number is positive")
else:
    print("The number is  negative")