# -*- coding: utf-8 -*-
"""CS-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iRk_gB8QyfkY0lCUrY8qM0UocBnz-WgO

Write a program to find whether a given year is a leap year or not.
"""

year = int(input("Enter any year:"))

if(year%400 == 0):
    print(year,"is leap year")
elif(year%100 == 0):
    print(year,"is not leap year")
elif(year%4 == 0):
    print(year,"is leap year")
else:
    print(year,"is not leap year")