# -*- coding: utf-8 -*-
"""CS-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4vnBc09vocRHgAJyMtFpqly-BELG_iw

Write a program to read the age of a candidate and determine whether it is eligible for casting his/her own vote
"""

age = int(input("Enter your age:"))
if(age>=18):
    print("Congratulation! You are eligible for casting your vote.")
else:
    print("You are not eligible for casting your own vote")