# -*- coding: utf-8 -*-
"""CS-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xzv8O_G7gREFVqqyo2FSy0MySHDnWKN9

Write a program to read the value of an integer m and display the value of n is 1 when m is larger than 0, 0 when m is 0 and -1 when m is less than 0
"""

m = int(input("Enter any number:"))

if(m>0):
    print("The value of N is 1")
elif(m==0):
    print("The value of N is 0")
else:
    print("The value of N is -1")