# -*- coding: utf-8 -*-
"""CS-7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xm_e1f9bL0U71euzc_Tf1ZWkPzhBo_Cr

Write a program to accept the height of a person in centimeter and categorize the person according to their height.
"""

personheight = float(input("Enter your height in Centimeter:"))

if(personheight<=150):
    print("The person is DWARf")
elif(personheight>=150 and personheight<165):
    print("Average Height")
elif(personheight>=165 and personheight<=195):
    print("The person is TALL")
else:
    print("Abnormal height")