# -*- coding: utf-8 -*-
"""CS-8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zwlKGxCfNjspzMVX_XriQ_R_6gziyEaj

Write a program to find the largest of three numbers
"""

num1 = int(input("Enter first number:"))
num2 = int(input("Enter second number:"))
num3 = int(input("Enter third number:"))

if(num1>num2):
    if(num1>num3):
        print("Number 1 is the largest")
    elif(num1<num3):
        print("Number 3 is the largest")
elif(num2>num1):
    if(num2>num3):
        print("Number 2 is the largest")
    elif(num2<num3):
        print("Number 3 is the largest")