# -*- coding: utf-8 -*-
"""CS-9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iQ2q3Sszu_EwbcV2j2FoYUNC1HK1qTUP

Write a program to accept a coordinate point in a XY coordinate system and determine in which quadrant the coordinate point lies
"""

x_coordinate = int(input("Enter X coordinate:"))
y_coordinate = int(input("Enter Y coordinate:"))

if(x_coordinate>0 and y_coordinate>0):
    print("The coordinate point (%s,%s) lies in the First quadrant." %(x_coordinate,y_coordinate))
elif(x_coordinate<0 and y_coordinate>0):
    print("The coordinate point ({x},{y}) lies in the Second quadrant.".format(x=x_coordinate, y=y_coordinate))
elif(x_coordinate<0 and y_coordinate<0):
    print(f"The coordinate point ({x_coordinate},{y_coordinate}) lies in the Third quadrant.")
elif(x_coordinate>0 and y_coordinate<0):
    print("The coordinate point" +"(" +str(x_coordinate)+","+str(y_coordinate)+")" +"lies in the Fourth quadrant.")
else:
    print("The coordinate you entered either lies on the center or on any of the axis")